const data=[
    {
      "title": "Los bancos de EEUU vuelan en la apertura de Wall Street y animan al sector financiero del Ibex",
      "author": "C. López",
      "published_date": "14 marzo 2023",
      "published_date_precision": true,
      "link": "https://www.epe.es/es/activos/20230314/bancos-eeuu-vuelan-apertura-wall-84636371",
      "image": "https://estaticos-cdn.epe.es/clip/aeca1158-3983-4e59-a73d-ef62317deea6_alta-libre-aspect-ratio_default_0.jpg",
      "summary": "El sector bancario estadounidense había sufrido una caída en las últimas sesiones, lo que llevó a la intervención de Silicon Valley Bank y Signature Bank. Sin embargo, tras la apertura de Wall Street, las cotizaciones experimentaron una fuerte subida, lo que animó a la gran banca española. El Sabadell subió un 4,50%, CaixaBank un 4,09%, BBVA un 3,42%, Santander un 3,02%, Bankinter un 2,83% y Unicaja un 2,06%. Además, el selectivo de la bolsa española se recuperó a 9.159 puntos. Los principales bancos estadounidenses también registraron subidas, aunque mostraron una menor volatilidad que las entidades de menor magnitud. La agencia de calificación crediticia Moody's ha empeorado su perspectiva sobre el sistema bancario de Estados Unidos, que baja a negativa desde estable, para reflejar el rápido deterioro en el entorno operativo tras el colapso de entidades como Silicon Valley Bank (SVB), Silvergate Bank y Signature Bank (SNY). Moody's espera que las presiones persistan y se vean exacerbadas por el actual endurecimiento de la política monetaria, además del aumento en los costes de los depósitos, lo que reducirá las ganancias de los bancos. Moody's anticipa que Estados Unidos entrará en una recesión leve en la última parte de 2023.",
      "topic": "Economía",
      "country": "EEUU",
      "language": "es",
      "is_opinion": false,
      "twitter_account": null,
      "score": null,
      "subtitle": "El Sabadell sube un 4,22% a media sesión, CaixaBank escala un 4,19%, Bankinter avanza un 3,04%, BBVV suma un 2,80%, el Santander se apunta un 2,60% y Unicaja se revaloriza un 2,34%",
      "clean_url": "elperiodico.es",
      "id": "1"
    },
    {
      "title": "Microsoft integrará un copiloto de inteligencia artificial en sus apps de ofimática",
      "author": "Ángel Jiménez de Luis",
      "published_date": "16 marzo 2023",
      "published_date_precision": true,
      "link": "https://www.elmundo.es/tecnologia/innovacion/2023/03/16/6413569bfc6c8329268b459c.html",
      "image": "https://phantom-elmundo.unidadeditorial.es/9e50545ba2e10f653dda36473dd8fa8a/resize/600/f/webp/assets/multimedia/imagenes/2023/03/16/16789885325641.jpg",
      "summary": "El nuevo modelo de lenguaje de OpenAI, GPT-4, ya está activo en ChatGPT y Bing Chat y es más preciso y capaz de razonar mejor que el modelo anterior, GPT-3. Microsoft integrará esta nueva tecnología en sus herramientas de ofimática, como Excel, Outlook, PowerPoint o Word, a través de una función llamada Microsoft 365 Copilot. Esta función permitirá a los usuarios trabajar con estas herramientas de manera diferente, permitiendo a Copilot escribir, resumir y editar textos siguiendo indicaciones en lenguaje natural, crear presentaciones a partir de descripciones, descubrir tendencias o generar gráficos con los datos de una hoja de cálculo, y crear automáticamente un resumen de todo lo que se ha hablado en una reunión. Copilot entiende el contenido y contexto de la empresa en la que se usa, y Microsoft ha programado varios cortafuegos y servicios de moderación para evitar que estas inteligencias artificiales muestren contenido no autorizado u ofensivo. La herramienta puede requerir el envío de datos a un servidor externo, pero Microsoft asegura que la información de las diferentes empresas no se usará para entrenar el modelo de lenguaje. Google también ha anunciado una estrategia similar para su suite de ofimática, que utilizará un modelo de lenguaje diferente a GPT-4.",
      "topic": "Tecnología",
      "country": "EEUU",
      "language": "es",
      "is_opinion": false,
      "twitter_account": null,
      "score": null,
      "subtitle": "La compañía lo va a integrar dentro de sus populares herramientas: Excel, Outlook, PowerPoint o Word",
      "clean_url": "elmundo.es",
      "id": "2"
    },
    {
      "title": "El Real Madrid se queda en la orilla ante el Efes (90-89)",
      "author": "José Manuel Martín",
      "published_date": "14 marzo 2023",
      "published_date_precision": true,
      "link": "https://www.larazon.es/deportes/real-madrid-queda-orilla-efes-9089_202303146410dc677262e50001aac15c.html",
      "image": "https://fotografias.larazon.es/clipping/cmsimages02/2023/03/14/F6683DF3-4320-4128-9263-E99A7EDD4589/97.jpg?crop=5112,2876,x0,y331&width=1600&height=900&optimize=low&format=webply",
      "summary": "El Real Madrid perdió contra el Anadolu Efes en un partido en el que estuvieron cerca de una histórica remontada. A pesar de las dificultades que tuvieron en Estambul, todo se definió por un punto y el Real Madrid remontó 17 puntos en el último cuarto. El Anadolu Efes ganó gracias a la actuación de su jugador Larkin, elegido MVP del partido, y a su espectacular juego de triples. El vigente campeón de la Euroliga, que busca su tercer título consecutivo, necesitaba ganar este partido para estar entre los ocho mejores equipos de la temporada. Los colegiados señalaron dos faltas técnicas por protestar a los blancos en un tercer cuarto con algunas decisiones dudosas y un espectáculo desde la larga distancia de los otomanos. El Real Madrid compitió hasta el último segundo y aunque perdió, fue un buen ensayo de lo que puede venir dentro de unas semanas. El Anadolu Efes busca su tercera corona consecutiva, pero el trabajo se ha complicado y ahora no pueden permitirse más tropiezos y menos en casa.",
      "topic": "Deportes",
      "country": "ES",
      "language": "es",
      "is_opinion": false,
      "twitter_account": null,
      "score": null,
      "subtitle": "Los blancos remontan 17 puntos en el último cuarto, pero no pueden rematar al vigente campeón, que se jugaba la vida",
      "clean_url": "larazon.es",
      "id": "3"
    },
    {
      "title": "Bruselas plantea una reforma 'light' del mercado eléctrico europeo para evitar los picos de precios",
      "author": "Beatríz Navarro",
      "published_date": "14 marzo 2023",
      "published_date_precision": true,
      "link": "https://www.lavanguardia.com/economia/20230314/8824320/bruselas-plantea-reforma-light-mercado-electrico-europeo-evitar-picos-precios.html",
      "image": "https://www.lavanguardia.com/files/image_948_465/uploads/2023/03/14/641084a340102.jpeg",
      "summary": "La Unión Europea está considerando la reforma de su mercado eléctrico debido a las consecuencias de la invasión rusa de Ucrania, que ha provocado facturas energéticas sin precedentes para los consumidores europeos. La Comisión Europea se ha alineado con países como Alemania y Países Bajos en su apuesta por una reforma light, mientras que España plantea cambios más estructurales. La reforma adoptada por el ejecutivo comunitario no cuestiona los fundamentos del sistema marginalista actual, pero introduce mecanismos correctores para limitar el papel del gas en la formación de precios y respaldar las inversiones en energías renovables y tecnología nuclear. Según la Comisión Europea, el sistema actual funciona bien y envía la señal correcta de precios a los consumidores.",
      "topic": "Economía",
      "country": "UE",
      "language": "es",
      "is_opinion": false,
      "twitter_account": null,
      "score": null,
      "subtitle": "La CE introduce mecanismos correctores para limitar el papel del gas en la formación de las tarifas eléctricas ",
      "clean_url": "lavanguardia.com",
      "id": "4"
    },
    {
      "title": "Los españoles queremos que nos olviden",
      "author": "Arantxa Herranz",
      "published_date": "13 marzo 2023",
      "published_date_precision": true,
      "link": "https://www.larazon.es/economia/startups/espanoles-queremos-que-nos-olviden_20230313640f29d2079ac900016e57d3.html",
      "image": "https://fotografias.larazon.es/clipping/cmsimages01/2022/12/22/24D3A198-75CD-4C75-85AD-9976779DB43F/97.jpg?crop=864,486,x2,y0&width=1600&height=900&optimize=low&format=webply",
      "summary": "Un estudio de Surfshark revela que entre 2015 y 2021 se presentaron más de un millón de solicitudes de derecho al olvido a Google y Microsoft Bing en Europa, siendo Francia el país con más solicitudes. España ocupa el cuarto lugar con 93.000 solicitudes, la mayoría de las cuales se presentaron a Google. Durante la pandemia de Covid-19, hubo un aumento del 30% en las solicitudes de derecho al olvido. En general, los solicitantes europeos pidieron eliminar una media de cuatro páginas web por petición a Google, y la mitad de las páginas solicitadas no podían clasificarse en una categoría específica. El derecho al olvido permite a las personas solicitar la eliminación de consultas relacionadas con su nombre de las páginas de resultados de los motores de búsqueda europeos.",
      "topic": "Tecnología",
      "country": "ES",
      "language": "es",
      "is_opinion": false,
      "twitter_account": null,
      "score": null,
      "subtitle": "Un estudio de las solicitudes para ejercer el derecho al olvido entre los buscadores asegura que los españoles estamos entre los europeos que más solicitan que se eliminen sus datos de los resultados de los buscadores.",
      "clean_url": "larazon.es",
      "id": "5"
    },
    {
      "title": "Alcaraz se mete en cuartos de final de Indian Wells tras la lesión de Jack Draper",
      "author": "Pablo Scarpellini",
      "published_date": "15 marzo 2023",
      "published_date_precision": true,
      "link": "https://www.elmundo.es/deportes/tenis/2023/03/15/64115fade4d4d8a27e8b45cc.html",
      "image": "https://phantom-elmundo.unidadeditorial.es/b29dcc89994de14e51291f0a42f0939b/crop/0x0/3071x2047/resize/600/f/webp/assets/multimedia/imagenes/2023/03/15/16788601624732.jpg",
      "summary": "El tenista español Carlos Alcaraz avanza a los cuartos de final del torneo de Indian Wells tras la retirada del británico Jack Draper al comienzo del segundo set. Después de perder el primer parcial 6-2, Draper se resentía de una lesión y dejó el camino libre para el joven tenista murciano. Alcaraz, en busca de superar su actuación del año pasado, salió enchufado desde el principio y mostró su fuerza y talento en la pista central de Indian Wells. Su próximo rival saldrá del encuentro entre Tommy Paul y Felix Auger-Aliassime. Si gana, se enfrentaría a una potencial semifinal contra Fritz o Sinner, en principio, y de ahí a una final contra Medvedev, Tiafoe o Norrie. Todo ello le pondría a las puertas del quinto grande y de recuperar el número uno del ranking por delante de Novak Djokovic.",
      "topic": "Deportes",
      "country": "EEUU",
      "language": "es",
      "is_opinion": false,
      "twitter_account": null,
      "score": null,
      "subtitle": "El murciano se imponía por 6-2 y 2-0 cuando el británico decidió abandonar el partido",
      "clean_url": "elmundo.es",
      "id": "6"
    },
    {
      "title": "Reforma: ¿cuántos años cotizados se tendrán en cuenta ahora para calcular mi pensión?",
      "author": "Inma Bermejo",
      "published_date": "16 marzo 2023",
      "published_date_precision": true,
      "link": "https://www.larazon.es/economia/reforma-cuantos-anos-cotizados-tendran-cuenta-ahora-calcular-pension_202303166413186c7262e50001adaeee.html",
      "image": "https://fotografias.larazon.es/clipping/cmsimages01/2022/02/21/C6207AE2-9900-40E7-B56B-77EBFEF2DEF9/97.jpg?crop=2301,1294,x0,y98&width=1600&height=900&optimize=low&format=webply",
      "summary": "El Gobierno de España ha aprobado una reforma de las pensiones que introduce un modelo dual para el cálculo de la pensión e incluye medidas para aumentar los ingresos del sistema, mejorar la suficiencia de las pensiones mínimas y reducir la brecha de género. La reforma introduce cambios en el periodo de cómputo de la pensión para que esta se calcule o con los últimos 25 años cotizados o con 29 años de cotización, de los que se podrán excluir los dos peores, por lo que en la práctica el cómputo en este segundo caso será de 27 años. Este régimen dual del periodo de cómputo estará vigente durante los próximos 20 años. La nueva opción que se introduce (29 años excluyendo dos) se desplegará progresivamente durante 12 años a partir de 2026, lo que beneficiará especialmente a los trabajadores con carreras irregulares. Además, la reforma contempla la subida progresiva de la base máxima de cotización y mejora el complemento para reducir la brecha de género en las pensiones.",
      "topic": "Economía",
      "country": "ES",
      "language": "es",
      "is_opinion": false,
      "twitter_account": null,
      "score": null,
      "subtitle": "La segunda parte de la reforma de las pensiones aprobada este jueves mantiene hasta 2044 el periodo de cómputo en los 25 años vigentes, aunque también será posible calcular la pensión con los últimos 29 años trabajados descartando los dos peores",
      "clean_url": "larazon.es",
      "id": "7"
    },
    {
      "title": "Estados Unidos amenaza con prohibir Tik Tok si los dueños chinos no venden sus acciones",
      "author": "Carles Planas Bou",
      "published_date": "16 marzo 2023",
      "published_date_precision": true,
      "link": "https://www.elperiodico.com/es/internacional/20230316/eeuu-amenaza-prohibir-tik-tok-84719433",
      "image": "https://estaticos-cdn.elperiodico.com/clip/05d6ce45-2f9a-4cfc-bd30-18a7d6807351_alta-libre-aspect-ratio_default_0.jpg",
      "summary": "El Gobierno de Estados Unidos ha anunciado que prohibirá la popular aplicación de vídeos TikTok si los accionistas chinos de su empresa propietaria, ByteDance, no se desprenden de sus acciones. La medida busca resolver las sospechas de que China está utilizando la aplicación para espiar a sus rivales, aunque estas acusaciones aún no han sido probadas. ByteDance ha estado negociando con Washington durante dos años para encontrar una solución a las preocupaciones estadounidenses sobre la protección de los datos de los más de 100 millones de usuarios de TikTok. Muchos estados de EE. UU., así como Canadá y la UE, han prohibido la aplicación entre sus funcionarios por preocupaciones de seguridad nacional. Según el Comité de Inversiones Extranjeras de EE. UU., los inversores chinos de ByteDance deberían vender sus acciones, lo que ha sido criticado por TikTok, que afirma que un cambio en la propiedad no resolvería el problema de seguridad.",
      "topic": "Tecnología",
      "country": "ES",
      "language": "es",
      "is_opinion": false,
      "twitter_account": null,
      "score": null,
      "subtitle": "Washington teme que China use la app para el espionaje y quiere forzar a los inversores chinos del gigante ByteDance a desprenderse de su participación",
      "clean_url": "elperiodico.com",
      "id": "8"
    },
    {
      "title": "El Real Madrid sella su clasificación sin sufrir ante un Liverpool inofensivo",
      "author": "Carlos Novos",
      "published_date": "15 marzo 2023",
      "published_date_precision": true,
      "link": "https://www.lavanguardia.com/deportes/real-madrid/20230315/8828893/victoria-sufrimiento.html",
      "image": "https://www.lavanguardia.com/files/image_948_465/uploads/2023/03/15/64123d3f6710d.jpeg",
      "summary": "El Real Madrid se clasificó para los cuartos de final de la Champions League tras un partido muy sólido ante el Liverpool, que no pudo remontar el resultado adverso de la ida en Anfield. El Madrid jugó con mucha seriedad y estuvo firme en defensa, mientras que el Liverpool no encontró las ocasiones de gol que necesitaba para seguir en la competición. El partido terminó con un gol de Benzema en los minutos finales que selló la victoria del Madrid. Klopp intentó sorprender con una alineación ofensiva, pero el Madrid se defendió bien y tuvo varias ocasiones para marcar. En la segunda parte, el Liverpool intentó apretar, pero sin éxito. El Madrid aprovechó la ocasión y logró el gol de la victoria. El partido acabó con el Bernabéu despidiendo al Liverpool con el himno You will never walk alone.",
      "topic": "Deportes",
      "country": "ES",
      "language": "es",
      "is_opinion": false,
      "twitter_account": null,
      "score": null,
      "subtitle": "Los blancos ganaron con un gol de Benzema a un rival que no pudo nunca meterse en la eliminatoria",
      "clean_url": "lavanguardia.com",
      "id": "9"
    },
    {
      "title": "Hacienda no ha hecho ni un pago aún del cheque de 200 euros mientras la inflación ahoga cada vez más a las familias",
      "author": "Daniel Viaña",
      "published_date": "16 marzo 2023",
      "published_date_precision": true,
      "link": "https://www.elmundo.es/economia/macroeconomia/2023/03/16/6411c8ede4d4d8907a8b458f.html",
      "image": "https://phantom-elmundo.unidadeditorial.es/9e11a4752389ae738ccbc3648ad8cf87/resize/600/f/webp/assets/multimedia/imagenes/2023/03/15/16789058294098.jpg",
      "summary": "El gobierno español aprobó hace más de tres meses un cheque de 200 euros para apoyar a las rentas de las familias de clase media en un contexto de inflación. A pesar de que el plazo para solicitarlo comenzó hace un mes, aún no se han realizado transferencias, según confirman en el Ministerio de Hacienda y la Agencia Tributaria. La ayuda está en periodo de solicitud hasta el último día de marzo, y la Agencia tiene un plazo de hasta tres meses para completar los abonos. El objetivo es llegar a 4,2 millones de hogares y evitar el fracaso de la anterior ayuda, que apenas llegó a 600,000 de las 2.7 millones de familias proyectadas. Los beneficiarios tendrán que incluir la percepción del cheque en su declaración del Impuesto sobre la Renta de las Personas Físicas del próximo año, y la cantidad neta del cheque será de 140 euros, con la Agencia Tributaria reteniendo 60 euros en impuestos.",
      "topic": "Economía",
      "country": "ES",
      "language": "es",
      "is_opinion": false,
      "twitter_account": null,
      "score": null,
      "subtitle": "La medida se aprobó hace ya más de tres meses, en los últimos días de 2022, y la Agencia Tributaria abrió el 15 de febrero el plazo para solicitar la ayuda",
      "clean_url": "elmundo.es",
      "id": "10"
    },
    {
      "title": "La impresión en 3D: un sector estratégico para TecnoCampus y Renfe",
      "author": "Javier Lucea",
      "published_date": "16 marzo 2023",
      "published_date_precision": true,
      "link": "https://www.lavanguardia.com/economia/innovacion/20230216/8762306/impresion-3d-sector-estrategico-tecnocampus-renfe-brl.html",
      "image": "https://www.lavanguardia.com/files/image_948_465/files/fp/uploads/2023/02/16/63ee2d6fd5ff8.r_d.2495-1432-3160.jpeg",
      "summary": "La empresa catalana Drukatt ha sido elegida como una de las ganadoras del concurso de aceleración de start-ups Antena TrenLab, promovido por Renfe y TecnoCampus, para mejorar el sistema de trenes de Renfe en Cataluña. Drukatt, especializada en la fabricación aditiva y la impresión 3D, presentó un proyecto holístico que incluye la difusión y formación en tecnología 3D, así como el análisis de componentes que pueden ser sustituidos gracias a la fabricación aditiva. La empresa recibió una prima de 40.000€ y una plaza en el acelerador. Drukatt tiene una cartera de 150 clientes de la industria de procesos y manufacturera, incluyendo grandes empresas como Repsol, SEAT o Endesa. Además, su capacidad de llevar a cabo procesos de fabricación híbrida es uno de sus principales elementos diferenciadores. Aunque la impresión 3D es una tecnología con capacidad transformadora, el director general de Drukatt señala que es importante buscar la mejor solución al problema o pieza que se necesite, y que esta puede o no pasar por dicha tecnología.",
      "topic": "Tecnología",
      "country": "ES",
      "language": "es",
      "is_opinion": false,
      "twitter_account": null,
      "score": null,
      "subtitle": "La empresa especializada en fabricación aditiva, Drukatt, ha empezado su estancia en la aceleradora Antena TrenLab en Mataró",
      "clean_url": "lavanguardia.com",
      "id": "11"
    },
    {
      "title": "Haaland, Messi y Luiz Adriano: el trío del repóquer de la Champions",
      "author": "Joan Domènech",
      "published_date": "15 marzo 2023",
      "published_date_precision": true,
      "link": "https://www.elperiodico.com/es/futbol/20230315/haaland-messi-trio-luiz-adriano-repoquer-goles-champions-84699152",
      "image": "https://estaticos-cdn.elperiodico.com/clip/b292c0d0-4aa7-4b1a-a6c7-6c2bcd4ceba8_alta-libre-aspect-ratio_default_0.jpg",
      "summary": "Erling Haaland es un futbolista noruego que tiene una gran habilidad para marcar goles desde que era joven. Después de anotar cinco goles en un partido con el Manchester City contra el Leipzig, Haaland dijo que su superpoder es marcar goles. Él se convirtió en el tercer jugador en la historia de la Champions League en anotar cinco goles en un partido, uniéndose a Lionel Messi y Luiz Adriano. Haaland es el más joven en alcanzar los 30 goles en la Champions League, necesitando solo 25 partidos para hacerlo, en comparación con Messi que necesitó 48 partidos y Cristiano Ronaldo que necesitó 74. Haaland está cerca de ingresar a los 30 primeros goleadores en la historia de la competición. Haaland comenzó a mostrar su habilidad goleadora en su debut en la liga y copa con el Molde a los 16 años y continuó marcando goles en el Salzburgo y el Dortmund antes de unirse al City en 2021.",
      "topic": "Deportes",
      "country": "ES",
      "language": "es",
      "is_opinion": false,
      "twitter_account": null,
      "score": null,
      "subtitle": "Solo tres futbolistas han marcado cinco goles en un partido de la Champions. El delantero noruego del Manchester City ha sido el más joven: a los 22 años.",
      "clean_url": "elperiodico.com",
      "id": "12"
    }
  ]